### ISSUE TITLE
Performances issues with large GIT repositories: Try to use index V4

### ISSUE THREAD

**Issue by staverne** [hforge/itools#98] opened 2017-05-05 16:45 UTC
On large repositories 42G (235M index), we have some performances issues on writing GIT index.
Maybe we can improve performances with index V4 (or with split index functionalities)
See documentation here: https://git-scm.com/docs/git-update-index

To use index V4 you should use git command:
`
  $ git update-index --index-version 4`

The index V4 is supported in libgit2 0.25

   https://github.com/libgit2/libgit2/pull/3837/commits/5625d86b994fd81f1b0d887890e8168d7b5f46cc

But the index is not yet supported with pygit2 ?

```
  File "/home/sylvain/projects/localhost/076/lib/python2.7/site-packages/itools/database/rw.py", line 240, in del_handler
    self.worktree.git_rm(key)
  File "/home/sylvain/projects/localhost/076/lib/python2.7/site-packages/itools/database/git.py", line 257, in git_rm
    index = self.index
  File "/home/sylvain/projects/localhost/076/lib/python2.7/site-packages/itools/database/git.py", line 216, in index
    index = self.repo.index
  File "/home/sylvain/projects/localhost/076/lib/python2.7/site-packages/pygit2/repository.py", line 477, in index
    check_error(err, True)
  File "/home/sylvain/projects/localhost/076/lib/python2.7/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: Invalid data in index - invalid entry
```

We should investigate / fix it & test if performances are better.

**Comment by staverne** [comment] 2017-05-05 16:48
@jdavid any advices to support index V4 in pygit2 ?

**Comment by jdavid** [comment] 2017-05-05 19:29
Best option would be to stop using the index/worktree.

Regarding index v4, since latest libgit2 supports it and pygit2 is just a wrapper, it should work. Can you reproduce the issue without itools, with a plain python/pygit2 script?

**Comment by staverne** [comment] 2017-05-06 11:50
This code

```
import subprocess
import pygit2

cwd = '/tmp/project.git/'
# 1) Create git repository
cmd = ['git', 'init', '/tmp/project.git/']
subprocess.call(cmd)
# 2) Set index version 4
cmd = ['git', 'update-index', '--index-version', '4']
subprocess.call(cmd, cwd=cwd)
# 3) Add file
f = open('/tmp/project.git/file.txt', 'w')
f.write('hello world')
f.close()
cmd = ['git', 'add', 'file.txt']
subprocess.call(cmd, cwd=cwd)
# 4) Commit
cmd = ['git', 'commit', '-m', 'first commit']
subprocess.call(cmd, cwd=cwd)
# 5) Try to open with libgit2/pygit2
repo = pygit2.Repository('/tmp/project.git/')
print dir(repo.index)
```

Generate this error:

```
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    print dir(repo.index)
  File "/home/sylvain/projects/localhost/076/lib/python2.7/site-packages/pygit2/repository.py", line 477, in index
    check_error(err, True)
  File "/home/sylvain/projects/localhost/076/lib/python2.7/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: Invalid data in index - extension is truncated

```

I use pygit2 version 0.25.1 and git version 2.12.2

**Comment by jdavid** [comment] 2017-05-09 13:48
Follow https://github.com/libgit2/libgit2/issues/4234

**Comment by staverne** [comment] 2017-05-09 17:16
Thank's 👍

**Comment by jdavid** [comment] 2017-07-06 15:55
libgit2/pygit2 0.26.0 released, this should be fixed, reopen if it is not
Thanks!

**Closed by jdavid** 2017-07-06 15:55 UTC
